### PR TITLE
Correct 2018 Extensions folder

### PR DESCRIPTION
**Pull request by tjackadams**
Update the extensions path for 2018 management studio

### CODE REVIEW

**Comment by gandarez** [comment]
Thanks!

**Comment by fspansk** [comment]
The wrong path is still there in the instructions on the official [webpage](https://wakatime.com/sql-server-management-studio). That anything you can fix, @gandarez?

**Comment by gandarez** [comment]
@fspansk the PR is still opened. I messaged Alan to approve that. Thanks.

**Comment by alanhamlett** [comment]
Fixed, thanks!

**Pull request merged**
